/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/availability": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Свободные моменты начала слотов для выбранного типа на [from, to).
         *     Длительность слота = durationMinutes типа. Учитываются все бронирования календаря.
         */
        get: operations["getAvailability"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Предстоящие бронирования всех типов в одном списке.
         *     Если `from` не передан, сервер использует текущий момент (UTC).
         *     Сортировка по `start` по возрастанию.
         */
        get: operations["listBookings"];
        put?: never;
        /** @description Создание брони; пересечение с любой существующей записью — 409. */
        post: operations["createBooking"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/event-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Список типов событий (для владельца и для страницы гостя). */
        get: operations["listEventTypes"];
        put?: never;
        /** @description Создание типа события. Клиент задаёт `id`; при дубле — 409. */
        post: operations["createEventType"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/event-types/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getEventType"];
        /** @description Полная замена полей типа (id только в пути). */
        put: operations["replaceEventType"];
        post?: never;
        /** @description Удаление типа; при невозможности (например есть брони) — 409. */
        delete: operations["deleteEventType"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/owner": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Возвращает единственного владельца календаря (синглтон). */
        get: operations["getOwner"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Тело ошибки API. */
        ApiError: {
            /**
             * Format: int32
             * @description Прикладной или HTTP-ориентированный код.
             */
            code: number;
            /** @description Человекочитаемое описание. */
            message: string;
        };
        /** @description Свободные слоты: моменты начала + параметр сетки, согласованный с сервером. */
        AvailabilityResponse: {
            /**
             * Format: int32
             * @description Шаг сетки слотов в минутах (например 15). Должен совпадать с query или значением по умолчанию.
             */
            slotStepMinutes: number;
            /** @description Допустимые моменты начала слота в UTC; каждый слот занимает duration выбранного типа. */
            availableStarts: string[];
        };
        /** @description 400 — неверные параметры или тело запроса. */
        BadRequestError: components["schemas"]["ApiError"];
        /** @description Бронирование. */
        Booking: {
            id: string;
            eventTypeId: string;
            /**
             * Format: date-time
             * @description Начало в UTC (ISO 8601).
             */
            start: string;
            guestName: string;
            guestEmail: string;
        };
        /** @description Элемент списка предстоящих бронирований с вложенным типом события. */
        BookingListItem: {
            id: string;
            eventTypeId: string;
            /** Format: date-time */
            start: string;
            guestName: string;
            guestEmail: string;
            eventType: components["schemas"]["EventTypeSummary"];
        };
        /**
         * @description Версии публичного HTTP API.
         * @enum {string}
         */
        CalendarApiVersions: "1.0.0";
        /** @description 409 — конфликт (дубль id типа, пересечение брони и т.п.). */
        ConflictError: components["schemas"]["ApiError"];
        /** @description Создание бронирования гостем. */
        CreateBookingRequest: {
            eventTypeId: string;
            /** Format: date-time */
            start: string;
            guestName: string;
            guestEmail: string;
        };
        /** @description Тело создания типа события (все поля ресурса, включая id). */
        CreateEventTypeRequest: {
            id: string;
            name: string;
            description: string;
            /** Format: int32 */
            durationMinutes: number;
        };
        /** @description Тип события: публичное представление и ресурс CRUD. */
        EventType: {
            /** @description Уникальный id; задаётся клиентом при создании (URL-safe строка). */
            id: string;
            name: string;
            description: string;
            /**
             * Format: int32
             * @description Длительность встречи в минутах (> 0 на стороне сервера).
             */
            durationMinutes: number;
        };
        /** @description Краткие данные типа в списке бронирований. */
        EventTypeSummary: {
            id: string;
            name: string;
            /** Format: int32 */
            durationMinutes: number;
        };
        /** @description 500 — внутренняя ошибка сервера. */
        InternalServerError: components["schemas"]["ApiError"];
        /** @description 404 — ресурс не найден. */
        NotFoundError: components["schemas"]["ApiError"];
        /**
         * @description Роль владельца календаря.
         * @enum {string}
         */
        OwnerRole: "Owner";
        /** @description Профиль владельца календаря (сейчас синглтон; схему можно расширять при эволюции API). */
        Profile: {
            /** @description Стабильный идентификатор профиля. */
            id: string;
            /** @description Отображаемое имя. */
            displayName: string;
            /** @description Контактный email. */
            email: string;
            role: components["schemas"]["OwnerRole"];
        };
        /** @description Тело полной замены типа события (PUT); id только в пути. */
        ReplaceEventTypeRequest: {
            name: string;
            description: string;
            /** Format: int32 */
            durationMinutes: number;
        };
        /** @description 422 — семантически неверный запрос (например слот вне сетки или в прошлом). */
        UnprocessableEntityError: components["schemas"]["ApiError"];
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getAvailability: {
        parameters: {
            query: {
                eventTypeId: string;
                from: string;
                to: string;
                /** @description Шаг сетки в минутах; если не указан — значение по умолчанию на сервере (отражается в ответе). */
                slotStepMinutes?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ответ 200 OK с JSON-телом. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AvailabilityResponse"];
                };
            };
            /** @description 400 — неверные параметры или тело запроса. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BadRequestError"];
                };
            };
            /** @description 404 — ресурс не найден. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundError"];
                };
            };
            /** @description 409 — конфликт (дубль id типа, пересечение брони и т.п.). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConflictError"];
                };
            };
            /** @description 422 — семантически неверный запрос (например слот вне сетки или в прошлом). */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnprocessableEntityError"];
                };
            };
            /** @description 500 — внутренняя ошибка сервера. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InternalServerError"];
                };
            };
        };
    };
    listBookings: {
        parameters: {
            query?: {
                /** @description Нижняя граница (UTC). По умолчанию — «сейчас» на сервере. */
                from?: string;
                /** @description Верхняя граница (UTC), опционально. */
                to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ответ 200 OK с JSON-телом. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingListItem"][];
                };
            };
            /** @description 400 — неверные параметры или тело запроса. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BadRequestError"];
                };
            };
            /** @description 404 — ресурс не найден. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundError"];
                };
            };
            /** @description 409 — конфликт (дубль id типа, пересечение брони и т.п.). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConflictError"];
                };
            };
            /** @description 422 — семантически неверный запрос (например слот вне сетки или в прошлом). */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnprocessableEntityError"];
                };
            };
            /** @description 500 — внутренняя ошибка сервера. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InternalServerError"];
                };
            };
        };
    };
    createBooking: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateBookingRequest"];
            };
        };
        responses: {
            /** @description Ответ 201 Created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"];
                };
            };
            /** @description 400 — неверные параметры или тело запроса. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BadRequestError"];
                };
            };
            /** @description 404 — ресурс не найден. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundError"];
                };
            };
            /** @description 409 — конфликт (дубль id типа, пересечение брони и т.п.). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConflictError"];
                };
            };
            /** @description 422 — семантически неверный запрос (например слот вне сетки или в прошлом). */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnprocessableEntityError"];
                };
            };
            /** @description 500 — внутренняя ошибка сервера. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InternalServerError"];
                };
            };
        };
    };
    listEventTypes: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ответ 200 OK с JSON-телом. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"][];
                };
            };
            /** @description 400 — неверные параметры или тело запроса. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BadRequestError"];
                };
            };
            /** @description 404 — ресурс не найден. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundError"];
                };
            };
            /** @description 409 — конфликт (дубль id типа, пересечение брони и т.п.). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConflictError"];
                };
            };
            /** @description 422 — семантически неверный запрос (например слот вне сетки или в прошлом). */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnprocessableEntityError"];
                };
            };
            /** @description 500 — внутренняя ошибка сервера. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InternalServerError"];
                };
            };
        };
    };
    createEventType: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateEventTypeRequest"];
            };
        };
        responses: {
            /** @description Ответ 201 Created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"];
                };
            };
            /** @description 400 — неверные параметры или тело запроса. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BadRequestError"];
                };
            };
            /** @description 404 — ресурс не найден. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundError"];
                };
            };
            /** @description 409 — конфликт (дубль id типа, пересечение брони и т.п.). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConflictError"];
                };
            };
            /** @description 422 — семантически неверный запрос (например слот вне сетки или в прошлом). */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnprocessableEntityError"];
                };
            };
            /** @description 500 — внутренняя ошибка сервера. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InternalServerError"];
                };
            };
        };
    };
    getEventType: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ответ 200 OK с JSON-телом. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"];
                };
            };
            /** @description 400 — неверные параметры или тело запроса. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BadRequestError"];
                };
            };
            /** @description 404 — ресурс не найден. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundError"];
                };
            };
            /** @description 409 — конфликт (дубль id типа, пересечение брони и т.п.). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConflictError"];
                };
            };
            /** @description 422 — семантически неверный запрос (например слот вне сетки или в прошлом). */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnprocessableEntityError"];
                };
            };
            /** @description 500 — внутренняя ошибка сервера. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InternalServerError"];
                };
            };
        };
    };
    replaceEventType: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReplaceEventTypeRequest"];
            };
        };
        responses: {
            /** @description Ответ 200 OK с JSON-телом. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"];
                };
            };
            /** @description 400 — неверные параметры или тело запроса. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BadRequestError"];
                };
            };
            /** @description 404 — ресурс не найден. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundError"];
                };
            };
            /** @description 409 — конфликт (дубль id типа, пересечение брони и т.п.). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConflictError"];
                };
            };
            /** @description 422 — семантически неверный запрос (например слот вне сетки или в прошлом). */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnprocessableEntityError"];
                };
            };
            /** @description 500 — внутренняя ошибка сервера. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InternalServerError"];
                };
            };
        };
    };
    deleteEventType: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ответ 204 No Content (без тела). */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 400 — неверные параметры или тело запроса. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BadRequestError"];
                };
            };
            /** @description 404 — ресурс не найден. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundError"];
                };
            };
            /** @description 409 — конфликт (дубль id типа, пересечение брони и т.п.). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConflictError"];
                };
            };
            /** @description 422 — семантически неверный запрос (например слот вне сетки или в прошлом). */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnprocessableEntityError"];
                };
            };
            /** @description 500 — внутренняя ошибка сервера. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InternalServerError"];
                };
            };
        };
    };
    getOwner: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ответ 200 OK с JSON-телом. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"];
                };
            };
            /** @description 400 — неверные параметры или тело запроса. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BadRequestError"];
                };
            };
            /** @description 404 — ресурс не найден. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotFoundError"];
                };
            };
            /** @description 409 — конфликт (дубль id типа, пересечение брони и т.п.). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConflictError"];
                };
            };
            /** @description 422 — семантически неверный запрос (например слот вне сетки или в прошлом). */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnprocessableEntityError"];
                };
            };
            /** @description 500 — внутренняя ошибка сервера. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InternalServerError"];
                };
            };
        };
    };
}
